### ISSUE TITLE
Chapter 1, Correlation, filtering through data gives an error.

### ISSUE THREAD

**Issue by r7asmu7s** [gedeck/practical-statistics-for-data-scientists#9] opened 2020-08-06 09:21 UTC
Chapter 1, the Correlation section, the first 2 cells give the same error,

TypeError                                 Traceback (most recent call last)
<ipython-input-21-fd53cd938bef> in <module>()
      4 
      5 # Filter data for dates July 2012 through June 2015
----> 6 telecom = sp500_px.loc[sp500_px.index >= '2012-07-01', telecomSymbols]
      7 telecom.corr()
      8 telecom

/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in cmp_method(self, other)
    120         else:
    121             with np.errstate(all="ignore"):
--> 122                 result = op(self.values, np.asarray(other))
    123 
    124         if is_bool_dtype(result):

TypeError: '>=' not supported between instances of 'numpy.ndarray' and 'numpy.ndarray'

FYI, I'm running the cells on Google Colab.

**Comment by gedeck** [comment] 2020-08-06 14:55
I cannot reproduce this. I opened the notebook in Google Colab and ran it without a problem. It also works fine in Python 3.6 and 3.8 on my computer with fresh installs of the environment.

The type error is really strange as numpy supports comparison between numpy arrays. Could it be that you have different versions of numpy installed? 

You could try the following and see if this works.
```
import numpy as np
telecom = sp500_px.loc[np.asarray(sp500_px.index) >= np.asarray('2012-07-01'), telecomSymbols]
telecom = sp500_px.loc[np.asarray(list(sp500_px.index)) >= np.asarray('2012-07-01'), telecomSymbols]
```
This would make sure that the same numpy is used for the comparison. Both commands work in my collab environment

**Comment by gedeck** [comment] 2020-08-11 01:46
@r7asmu7s I don't really know what to do here. As I cannot reproduce it, I will close this issue. If you try my suggested workaround and it works, please add a comment here.

**Closed** 2020-09-08 15:44 UTC
