### ISSUE TITLE
Errors and Questions in Ch5, 6, 7

### ISSUE THREAD

**Issue by deulkkae** [gedeck/practical-statistics-for-data-scientists#15] opened 2021-02-22 06:06 UTC
### 1. In Chapter 5, some notebook code results are diffrent with printed book's.
**[Confusion Matrix]**
```
In [18]:
# Confusion matrix
pred <- predict(logistic_gam, newdata=loan_data)
pred_y <- as.numeric(pred > 0)
true_y <- as.numeric(loan_data$outcome=='default')
true_pos <- (true_y==1) & (pred_y==1)
true_neg <- (true_y==0) & (pred_y==0)
false_pos <- (true_y==0) & (pred_y==1)
false_neg <- (true_y==1) & (pred_y==0)
conf_mat <- matrix(c(sum(true_pos), sum(false_pos),
                     sum(false_neg), sum(true_neg)), 2, 2)
colnames(conf_mat) <- c('Yhat = 1', 'Yhat = 0')
rownames(conf_mat) <- c('Y = 1', 'Y = 0')
conf_mat
```
  | Yhat = 1 | Yhat = 0
-- | -- | --
Y  |14293 | 8378
Y  |8051 | 14620

In the R notebook, the correctly predicted defaults are 14,293 and incorrectly predicted ones are 8,378. But, in the printed book they are 14,295 and 8,376.

And in Python, I got the another diffrent numbers.
```
    Yhat = default  Yhat = paid off
Y = default       14336        8335
Y = paid off        8148      14523
```

Which one is correctly right? If the notebook's results are right, the numbers in the first paragrahp of page 222 should be edited. 

### 2. It's also about the diffrent code results in printed book.

**[AUC]**
```
In [21]: 
sum(roc_df$recall[-1] * diff(1-roc_df$specificity))
head(roc_df)
0.692623197044616
```

The result in notebook is 0.692623197044616, but it is 0.6926172 in the book book. Please check the Python code and result too. 

### 3. XGBoost was updated 1.3.0, so it bring some errors in codes, in Chapter 6 and 7(page 272, 275, 276, 280).
It's okay to excutue the codes till to page 276. But without explicitly setting eval_metric="error", you will finally get errors in page 280. I think it would be better to edit github's codes. 

### 4. In Chapter 7, K-Means Clustering - A Simple Example

```
In [12]:
set.seed(1010103)
df <- sp500_px[row.names(sp500_px)>='2011-01-01', c('XOM', 'CVX')]
km <- kmeans(df, centers=4, nstart=1)

df$cluster <- factor(km$cluster)
head(df)
XOM	CVX	cluster
2011-01-03	0.73680496	0.2406809	1
2011-01-04	0.16866845	-0.5845157	4
2011-01-05	0.02663055	0.4469854	1
2011-01-06	0.24855834	-0.9197513	4
2011-01-07	0.33732892	0.1805111	1
2011-01-10	0.00000000	-0.4641675	4
```

In the nodebook the first six records are assigned to either cluster 1 or clust 4. The meas of the clusters are the below. 

```
In [13]:
centers <- data.frame(cluster=factor(1:4), km$centers)
centers

cluster	XOM	CVX
1	 0.2315403	 0.3169645
2	 0.9270317	 1.3464117
3	-1.1439800	-1.7502975
4	-0.3287416	-0.5734695
```

But the excution results in the book are little bit different. They are assigned to cluster 1 or 2. However, as you see the [Figur 7-5], the cluster 3 and 4 are in the minus area(left below of the graph). and it looks like they represent "down" market. So, I think the code results and some sentences in page 296~297 should be changed. 

### 5. In Chapter 7, in page 323, the first line of the date table bring wrong column. 

```
> x <- loan_data[1:5, c('dti', 'payment_inc_ratio', 'home_', 'purpose_')]
> x

    dti payment_inc_ratio   home             purpose  
  <dbl>             <dbl> <fctr>             <fctr>
1  1.00           2.39320   RENT                car
...

```

It should be changed like this. 

```
> x <- loan_data[1:5, c('dti', 'payment_inc_ratio', 'home_', 'purpose_')]
> x

    dti payment_inc_ratio   home_             purpose_  
  <dbl>             <dbl> <fctr>             <fctr>
1  1.00           2.39320   RENT                major_purchase
...

```

Please check them all and let me know if I think(or did) something wrong. :) Thanks in advance.

**Comment by gedeck** [comment] 2021-02-23 03:23
(1) There isn't really one right confusion matrix. If you'd compare the confusion matrix to the first edition, you would see that the confusion matrix was very different then. That was due to a different `logistic_gam` model. You will see that more complex models can often change when implementations change (in particular if there is a random component). I assume that when I checked the R code and copied the output into the book source, the output was as it is shown now. There was maybe a small change in the meantime that caused the shift of a few predictions. I reran the code with a fresh R installation and get the results from the R notebook. Will change the book's source to reflect this difference.

Python is using a different implementation of the splines and it's therefore to be expected that the model will predict differently.

(2) follows from (1) and corrected the book result. Note however that the results are identical to 5 digits 0.69262. For accuracy, I would normally not report more than 3 digits (0.693) and only in rare occasions 4.

**Comment by gedeck** [comment] 2021-02-23 03:55
(3) thanks for pointing that out. I'll rerun all code with the latest versions of R and Python and update the repository. 

(4) I'm not going to change the book. The assignment and numbering of clusters is not unique as there is a random component in the k-means algorithm that will lead to these variations. 

(5) I can confirm this and modified the book source code. This is a left over from the first edition and I assume that at some point car was changed to major_purchase and possibly combined with other purposes.

**Comment by gedeck** [comment] 2021-02-23 16:24
I've rerun all notebooks with latest package versions for R and Python and adjusted code if required (e.g. seaborn calls).

I'm going to close this issue. @deulkkae, if there is anything not addressed, let me know.

**Closed by gedeck** 2021-02-23 16:24 UTC

**Comment by deulkkae** [comment] 2021-02-26 02:19
### Naive Bayes, The Naive Solution 
The predicted probabilities results are different. They should be 0.4798964(paid off) 0.5201036(default). 

I ran the code in colab. Would check this notebook?
https://colab.research.google.com/drive/1ChitMlzaMHYDru6ngI1qBHhJGcIP-RhI#scrollTo=1EnynWD14l2R&line=7&uniqifier=1


### Variable importance
Need line-break in line 318. 
https://github.com/gedeck/practical-statistics-for-data-scientists/blob/3e1bf1cb3ca3f345195f702addc3a3b01e67c58c/python/code/Chapter%206%20-%20Statistical%20Machine%20Learning.py#L318

### Hyperparameters and Cross-Validation
Need line-break in 453
https://github.com/gedeck/practical-statistics-for-data-scientists/blob/3e1bf1cb3ca3f345195f702addc3a3b01e67c58c/python/code/Chapter%206%20-%20Statistical%20Machine%20Learning.py#L453

And line 452 has type error. Would check this line?
https://github.com/gedeck/practical-statistics-for-data-scientists/blob/3e1bf1cb3ca3f345195f702addc3a3b01e67c58c/python/code/Chapter%206%20-%20Statistical%20Machine%20Learning.py#L452
"TypeError: Object with dtype category cannot perform the numpy op subtract"

### Python XGBoost codes in Ch6
It would be better to set eval_metric='error' in Python codes too.
